/* @flow */

import type { SourceAny, SourceFixed,
              TaskTypeProvision, TaskTypeUpgrade, TaskTypeBuild, TaskTypeMine,
              EnergyTargetTypeSpawn, EnergyTargetTypeController, EnergyTargetTypeConstruction,
              CreepMemoryVersion, RoomMemoryVersion } from "../types/ConstTypes.js"

export const CREEP_MEMORY_VERSION : CreepMemoryVersion = "0.0.1";
export const ROOM_MEMORY_VERSION : RoomMemoryVersion = "0.0.1";

const TASK_PRIO_MAX = 1000000;

export const TaskPriorities = {
    MIN:             0,
    SUSPENDED:      10,
    IDLE:          100,
    UPGRADE:      1000,
    UPKEEP:      10000,
    URGENT:     100000,
    IMMEDIATE: 1000000,
    MAX: TASK_PRIO_MAX
}

export const TaskStates = {
    WAITING: "WAITING",
    ASSIGNED: "ASSIGNED",
    RUNNING: "RUNNING",
    BLOCKED: "BLOCKED",
    FINISHED: "FINISHED",
    ABORTED: "ABORTED"
}

export const TaskTypes = {
    PROVISION: ("PROVISION": TaskTypeProvision),
    UPGRADE: ("UPGRADE": TaskTypeUpgrade),
    BUILD: ("BUILD": TaskTypeBuild),
    MINE: ("MINE": TaskTypeMine)
}

export const TaskStepTypes = {
    NOOP: "NOOP",
    NAVIGATE: "NAVIGATE",
    HARVEST: "HARVEST",
    TRANSFER: "TRANSFER",
    UPGRADE: "UPGRADE",
    BUILD: "BUILD",
    PICKUP: "PICKUP"
}

export const SourceTargets = {
    ANY: ("SOURCE_ANY": SourceAny),
    FIXED: ("SOURCE_FIXED": SourceFixed)
}

export const CreepStates = {
    IDLE: "IDLE",
    BLOCKED: "BLOCKED",
    SUSPENDED: "SUSPENDED",
    BUSY: "BUSY",
    PANIC: "PANIC"
}

export const EnergyTargetTypes = {
    SPAWN: ("SPAWN": EnergyTargetTypeSpawn),
    CONTROLLER: ("CONTROLLER": EnergyTargetTypeController),
    CONSTRUCTION: ("CONSTRUCTION": EnergyTargetTypeConstruction)
}

export const ENERGY_CAPACITY_MAX = {
    "1": CONTROLLER_STRUCTURES[STRUCTURE_SPAWN][1] * SPAWN_ENERGY_CAPACITY + CONTROLLER_STRUCTURES[STRUCTURE_EXTENSION][1] * EXTENSION_ENERGY_CAPACITY[1],
    "2": CONTROLLER_STRUCTURES[STRUCTURE_SPAWN][2] * SPAWN_ENERGY_CAPACITY + CONTROLLER_STRUCTURES[STRUCTURE_EXTENSION][2] * EXTENSION_ENERGY_CAPACITY[2],
    "3": CONTROLLER_STRUCTURES[STRUCTURE_SPAWN][3] * SPAWN_ENERGY_CAPACITY + CONTROLLER_STRUCTURES[STRUCTURE_EXTENSION][3] * EXTENSION_ENERGY_CAPACITY[3],
    "4": CONTROLLER_STRUCTURES[STRUCTURE_SPAWN][4] * SPAWN_ENERGY_CAPACITY + CONTROLLER_STRUCTURES[STRUCTURE_EXTENSION][4] * EXTENSION_ENERGY_CAPACITY[4],
    "5": CONTROLLER_STRUCTURES[STRUCTURE_SPAWN][5] * SPAWN_ENERGY_CAPACITY + CONTROLLER_STRUCTURES[STRUCTURE_EXTENSION][5] * EXTENSION_ENERGY_CAPACITY[5],
    "6": CONTROLLER_STRUCTURES[STRUCTURE_SPAWN][6] * SPAWN_ENERGY_CAPACITY + CONTROLLER_STRUCTURES[STRUCTURE_EXTENSION][6] * EXTENSION_ENERGY_CAPACITY[6],
    "7": CONTROLLER_STRUCTURES[STRUCTURE_SPAWN][7] * SPAWN_ENERGY_CAPACITY + CONTROLLER_STRUCTURES[STRUCTURE_EXTENSION][7] * EXTENSION_ENERGY_CAPACITY[7],
    "8": CONTROLLER_STRUCTURES[STRUCTURE_SPAWN][8] * SPAWN_ENERGY_CAPACITY + CONTROLLER_STRUCTURES[STRUCTURE_EXTENSION][8] * EXTENSION_ENERGY_CAPACITY[8]
}
